### ISSUE TITLE
AttributeError: module 'tensorflow.tools.api.generator.api.logging' has no attribute '_logger'

### ISSUE THREAD

**Issue by siddas27** [DongjunLee/dmn-tensorflow#1]
When I executed
`python main.py --config bAbi_task1 --mode train_and_evaluate `
    it throws the following error:
```
Traceback (most recent call last):
  File "main.py", line 96, in <module>
    tf.logging._logger.setLevel(logging.INFO)
AttributeError: module 'tensorflow.tools.api.generator.api.logging' has no attribute '_logger'
```
Please help me out.

**Comment by DongjunLee** [comment]
The problem is the TensorFlow version.
Could you excute it with tensorflow 1.4 version?

**Comment by siddas27** [comment]
Yeah, I have version is 1.8. I fixed it using `tf.logging.set_verbosity(logging.INFO)` in place of `tf.logging._logger.setLevel(logging.INFO)`

**Comment by DongjunLee** [comment]
Great :)

**Comment by lmukesh1807** [comment]
# Reduce logging output.
following error how to fix?
--->  tf.logging.set_verbosity(tf.logging.ERROR)
  

AttributeError: module 'tensorflow' has no attribute 'logging'

**Comment by DongjunLee** [comment]
Change the code
```tf.logging.set_verbosity(logging.INFO``` => ```tf.logging._logger.setLevel(logging.INFO)```

**Comment by lmukesh1807** [comment]
Thank you for your support

**Comment by lmukesh1807** [comment]
Hi sir how to work on production in tensorflow serving
