### ISSUE TITLE
Pre-implementation query

### ISSUE THREAD

**Issue by Brook4846** [DongjunLee/dmn-tensorflow#4]
I've went through the DMN paper and have seen some of the examples they presented for the question answering  implementation using the bAbi dataset and wanted to know weather we can acquire more than a one word answer before trying out this implementation.

**Comment by DongjunLee** [comment]
The answer module in paper is GRU (RNN), so you can acquire more than a one word.
But my implementation acquires only one word.

**Comment by Brook4846** [comment]
Well that's reassuring. Would you be kind enough to send me links of these implementations on Github if there are any you're aware of.

**Comment by DongjunLee** [comment]
Sorry, I don't know it.

**Comment by Brook4846** [comment]
Well, thanks anyway...
